//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachoManFFStats.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Standings = new HashSet<Standing>();
        }
    
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Standing> Standings { get; set; }
    }
}
