//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachoManFFStats.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standing
    {
        public int StandingsID { get; set; }
        public int Season { get; set; }
        public int MemberID { get; set; }
        public int RegularSeasonRank { get; set; }
        public bool IsChampion { get; set; }
        public bool ReachedFinals { get; set; }
        public bool MadePlayoffs { get; set; }
        public bool ReceivedBye { get; set; }
        public bool DivisionWinner { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
