//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachoManFFStats.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAllTimeStanding
    {
        public int MemberId { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> PointsScored { get; set; }
        public Nullable<int> PointsAgainst { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Losses { get; set; }
        public Nullable<decimal> WinPercentage { get; set; }
    }
}
