//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachoManFFStats.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHistoricalMatchup
    {
        public int MatchupID { get; set; }
        public int Week { get; set; }
        public int Year { get; set; }
        public Nullable<int> HomeMemberID { get; set; }
        public string HomeTeam { get; set; }
        public int HomeScore { get; set; }
        public Nullable<int> AwayMemberID { get; set; }
        public string AwayTeam { get; set; }
        public int AwayScore { get; set; }
    }
}
