//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachoManFFStats.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vRecordVsOpponent
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public int OppMemberID { get; set; }
        public string OppName { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
    }
}
